---
title: "Analysis of Growth Rates of Parents and Rif-R Strains"
output: pdf_document
author: Sriya Sunil
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(tidyverse)
library(reshape2)
library(gridExtra)
library(emmeans)
library(lme4)
library(lmerTest)
library(RColorBrewer)
```

```{r}
counts_df <- read.csv("CombinedCounts.csv", header = T)
counts_melt_df <- melt(counts_df, id.vars = "Plate_Id")
counts_log <- log(counts_melt_df$value, base = 10)
counts_log_melt_df <- cbind(counts_melt_df[,c(1,2)], counts_log)
counts_log_melt_df$Plate_Id <- as.character(counts_log_melt_df$Plate_Id)
isolate_ID <- vapply(strsplit(counts_log_melt_df$Plate_Id, "_"), function(x) paste(x[1:2], collapse = "-"), FUN.VALUE = character(1L))
Replicate_ID <- vapply(strsplit(counts_log_melt_df$Plate_Id, "_"), '[', 3, FUN.VALUE = character(1))
finaldf <- data.frame(cbind(isolate_ID, Replicate_ID, counts_log_melt_df))
colnames(finaldf)[1:2] <- c("Isolate_ID", "Replicate_ID")
wt <- c("M9-0536", "M9-0538", "M9-0540", "M9-0610", "M9-0617", "S12-0061", "S12-0074", "M9-0544", "M9-0547", "M9-0550", "M9-0606", "S12-0025", "S12-0004", "S12-0048", "S12-0063")
rif <- c("S12-0116", "S12-0126", "S12-0132", "S12-0150", "S12-0156", "S12-0173", "S12-0184", "S12-0139", "S12-0188", "S12-0195", "S12-0141", "S12-0151", "S12-0166", "S12-0163", "S12-0180")
```

```{r}
d0_d3 <- (log(counts_df$Day_3,base = 10) - log(counts_df$Day_0, base = 10))
d3_d6 <- (log(counts_df$Day_6,base = 10) - log(counts_df$Day_3, base = 10))

net_growth_table <- data.frame(cbind(counts_df$Plate_Id, d0_d3, d3_d6))
colnames(net_growth_table) <- c("Isolate_ID", "Day_0-3", "Day_3-6")
melt_net_growth_table <- melt(net_growth_table, id.vars = "Isolate_ID")
isolate_ID_mu <- vapply(strsplit(melt_net_growth_table$Isolate_ID, "_"), function(x) paste(x[1:2], collapse = "-"), FUN.VALUE = character(1L))
Replicate_ID_mu <- vapply(strsplit(melt_net_growth_table$Isolate_ID, "_"), '[', 3, FUN.VALUE = character(1))
net_growth_df <- cbind(isolate_ID_mu, Replicate_ID_mu, melt_net_growth_table[,2:3])
colnames(net_growth_df)[1:3] <- c("Isolate_ID", "Replicate_ID", "Duration")
net_growth_df$value <- as.numeric(net_growth_df$value)


change_summary <- net_growth_df %>%
  group_by(Isolate_ID, Duration) %>%
  summarize(mean = round(mean(value), 2), sd = round(sd(value), 2))
  
```


```{r}
#FSL M9-0536 & FSL S12-0116

finaldf$variable <- as.factor(finaldf$variable)
finaldf$Isolate_ID <- as.factor(finaldf$Isolate_ID)

df_1 <- subset(finaldf, isolate_ID %in% c(wt[1], rif[1]))
mod_1 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_1)
mod.emm_1 <- emmeans(mod_1, ~ Isolate_ID + variable)
con_1 <- contrast(mod.emm_1, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[1], "(Parent) &", rif[1], "(Rif-R)", sep = " "))
print(summary(con_1))

#FSL M9-0538 & FSL S12-0126

df_2 <- subset(finaldf, isolate_ID %in% c(wt[2], rif[2]))
mod_2 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_2)
mod.emm_2 <- emmeans(mod_2, ~ Isolate_ID + variable)
con_2 <- contrast(mod.emm_2, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[2], "(Parent) &", rif[2], "(Rif-R)", sep = " "))
print(summary(con_2))

#FSL M9-0540 & FSL S12-0132

df_3 <- subset(finaldf, isolate_ID %in% c(wt[3], rif[3]))
mod_3 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_3)
mod.emm_3 <- emmeans(mod_3, ~ Isolate_ID + variable)
con_3 <- contrast(mod.emm_3, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[3], "(Parent) &", rif[3], "(Rif-R)", sep = " "))
print(summary(con_3))

#FSL M9-0610 & FSL S12-0150

df_4 <- subset(finaldf, isolate_ID %in% c(wt[4], rif[4]))
mod_4 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_4)  #Boundary is singular. Will use "lm"
mod_4 <- lm(counts_log ~ variable * Isolate_ID, data = df_4) 
mod.emm_4 <- emmeans(mod_4, ~ Isolate_ID + variable)
con_4 <- contrast(mod.emm_4, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[4], "(Parent) &", rif[4], "(Rif-R)", sep = " "))
print(summary(con_4))

#FSL M9-0617 & FSL S12-0156

df_5 <- subset(finaldf, isolate_ID %in% c(wt[5], rif[5]))
mod_5 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_5)
mod.emm_5 <- emmeans(mod_5, ~ Isolate_ID + variable)
con_5 <- contrast(mod.emm_5, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[5], "(Parent) &", rif[5], "(Rif-R)", sep = " "))
print(summary(con_5))

#FSL S12-0061 & FSL S12-0173

df_6 <- subset(finaldf, isolate_ID %in% c(wt[6], rif[6]))
mod_6 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_6)
mod.emm_6 <- emmeans(mod_6, ~ Isolate_ID + variable)
con_6 <- contrast(mod.emm_6, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[6], "(Parent) &", rif[6], "(Rif-R)", sep = " "))
print(summary(con_6))

#FSL S12-0074 & FSL S12-0184

df_7 <- subset(finaldf, isolate_ID %in% c(wt[7], rif[7]))
mod_7 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_7) #Boundary is singular. Will use "lm"
mod_7 <- lm(counts_log ~ variable * Isolate_ID, data = df_7)
mod.emm_7 <- emmeans(mod_7, ~ Isolate_ID + variable)
con_7 <- contrast(mod.emm_7, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[7], "(Parent) &", rif[7], "(Rif-R)", sep = " "))
print(summary(con_7))

#FSL M9-0544 & FSL S12-0139

df_8 <- subset(finaldf, isolate_ID %in% c(wt[8], rif[8]))
mod_8 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_8) 
mod.emm_8 <- emmeans(mod_8, ~ Isolate_ID + variable)
con_8 <- contrast(mod.emm_8, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[8], "(Parent) &", rif[8], "(Rif-R)", sep = " "))
print(summary(con_8))

#FSL M9-0547 & FSL S12-0188

df_9 <- subset(finaldf, isolate_ID %in% c(wt[9], rif[9]))
mod_9 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_9) 
mod.emm_9 <- emmeans(mod_9, ~ Isolate_ID + variable)
con_9 <- contrast(mod.emm_9, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[9], "(Parent) &", rif[9], "(Rif-R)", sep = " "))
print(summary(con_9))

#FSL M9-0550 & FSL S12-0195

df_10 <- subset(finaldf, isolate_ID %in% c(wt[10], rif[10]))
mod_10 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_10) 
mod.emm_10 <- emmeans(mod_10, ~ Isolate_ID + variable)
con_10 <- contrast(mod.emm_10, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[10], "(Parent) &", rif[10], "(Rif-R)", sep = " "))
print(summary(con_10))

#FSL M9-0606 & FSL S12-0141

df_11 <- subset(finaldf, isolate_ID %in% c(wt[11], rif[11]))
mod_11 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_11) 
mod.emm_11 <- emmeans(mod_11, ~ Isolate_ID + variable)
con_11 <- contrast(mod.emm_11, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[11], "(Parent) &", rif[11], "(Rif-R)", sep = " "))
print(summary(con_11))

#FSL S12-0025 & FSL S12-0151

df_12 <- subset(finaldf, isolate_ID %in% c(wt[12], rif[12]))
mod_12 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_12) #Boundary is singular. Will use "lm"
mod_12 <- lm(counts_log ~ variable * Isolate_ID, data = df_12)
mod.emm_12 <- emmeans(mod_12, ~ Isolate_ID + variable)
con_12 <- contrast(mod.emm_12, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[12], "(Parent) &", rif[12], "(Rif-R)", sep = " "))
print(summary(con_12))

#FSL S12-0004 & FSL S12-0166

df_13 <- subset(finaldf, isolate_ID %in% c(wt[13], rif[13]))
mod_13 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_13) #Boundary is singular. Will use "lm"
mod_13 <- lm(counts_log ~ variable * Isolate_ID, data = df_13) 
mod.emm_13 <- emmeans(mod_13, ~ Isolate_ID + variable)
con_13 <- contrast(mod.emm_13, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[13], "(Parent) &", rif[13], "(Rif-R)", sep = " "))
print(summary(con_13))

#FSL S12-0048 & FSL S12-0163

df_14 <- subset(finaldf, isolate_ID %in% c(wt[14], rif[14]))
mod_14 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_14) 
mod.emm_14 <- emmeans(mod_14, ~ Isolate_ID + variable)
con_14 <- contrast(mod.emm_14, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[14], "(Parent) &", rif[14], "(Rif-R)", sep = " "))
print(summary(con_14))

#FSL S12-0063 & FSL S12-0180

df_15 <- subset(finaldf, isolate_ID %in% c(wt[15], rif[15]))
mod_15 <- lmer(counts_log ~ variable * Isolate_ID + (1|Plate_Id), data = df_15) 
mod.emm_15 <- emmeans(mod_15, ~ Isolate_ID + variable)
con_15 <- contrast(mod.emm_15, method = list("first_netgrowth" = c(-1, 1, 1, -1, 0, 0), "second_netgrowth" = c(0, 0, -1, 1, 1, -1)))
print(paste("Comparison of net growth for", wt[15], "(Parent) &", rif[15], "(Rif-R)", sep = " "))
print(summary(con_15))

```

```{r}
write.csv(change_summary, "net_growth_by_day.csv", row.names = FALSE)
```

